#!/bin/bash
set -e
FILENAME=${1}

LOWER=$(cat /proc/mounts | grep "overlay" | head -1 | sed 's/.*lowerdir=\([^,]*\).*/\1/')
if [ -z "${LOWER}" ]; then
    echo "ERROR: could not determine lower mount" >&2
    exit 1
fi

DIRNAME=$(dirname ${FILENAME})
if [[ ${DIRNAME:0:1} == "/" ]]; then
    rsync ${FILENAME} ${LOWER}${FILENAME}
else
    rsync ${FILENAME} ${LOWER}${PWD}/${FILENAME}
fi
