[modbus]
port = 502
slave_address = 255

[gpio]
num_outputs = 8
do_register = 0x0001
polarity = active_high

##### GPIO pin numbers (sysfs) #####################################
# PH6 = 7*32+6 = 230
do0 = 230
# PH8 = 7*32+8 = 232
do1 = 232
# PH7 = 7*32+7 = 231
do2 = 231
# PC8 = 2*32+8 = 72
do3 = 72
# PC5 = 2*32+5 = 69
do4 = 69
# PC6 = 2*32+6 = 70
do5 = 70
# PH4 = 7*32+4 = 228
do6 = 228
# PH5 = 7*32+5 = 229
do7 = 229
